# EMERGENY INFORMATION

## CAMPUS SAFETY: (909) 607-2000
When in doubt, just call Campus Safety at **(909) 607-2000**.

## Our Location
If you have to call Campus Safety and direct them to our location, please say ***"we are in the QCL in LC29. This is the south side of the Kravis Lower Court next to the Veterns Patio."***

If you have to call an external paramedics and direct them to our location, please say ***"we are located just east of 888 N. Columbia Avenue. We are in the lower court area immediately underneath the glass cube surrounded by water on campus. If you go down the stairs immediately south of the cube, you should see a sign for the Murty Sunak Quantitative and Computing Lab in the corner. We are in there."***

## First Aid
We keep a first aid kit on top of the fridge. We also have a supplementary first aid kit and bandages in the right-most kitchen drawer for needs that aren't necessarily an emergency. 

## Fire Safety
A fire extinguisher is located adjacent to the front door. 

## Earthquake Safety
(Need to add safe location)

## QCL Staff Cell Numbers
Jeho Park (Director): (714) 326 dash 7277

Bhaven Mistry (Asst. Director): (805) 285 dash 2428

Janna Shwaiko (Admin. Assistant): (909) 532 dash 0075