# Walk-in Sessions

## Time

- Sundays to Thursdays, from 7pm to 9pm
- We often close for holidays, including Thanksgiving and Spring Break
  - We care about our Mentors getting a break
- Changes to our Walk-in schedule will always be emailed out to CMC students
  - Non-CMC students will not receive these emails.
  
## General Procedure

- Show up to the QCL on the nights you are assigned punctually
  - Head mentors will mark you tardy if you are
- Check in with one of the Head Mentors to let them know you are here
  - They mark attendance, but also need to know who they can delegate mentors to
- Wait for mentors who need help inside the QCL Lounge
  - They might be delegated to you by a Head Mentor or the student might just walk up to you.
  - In the mean time, you can do homework or chat with fellow mentors, but proactively look for students who need help.
  - Do not hide inside a close room somewhere to finish studying or some homework; you are here to help other students, so make yourself present and available.
  
## During the session

- Have the mentee scan your check-in QR code
  - This is located on the back side of your QCL badge
  - If you are in the middle of a group session, still require each new student that walks up to scan the QR code
  
## Head Mentors Are In Charge

- They are managing the entire session
- They check your attendance and report directly to the QCL Directors about problems
- They delegate mentees to mentors.
- They also manage the logistics and clean-up of the session.
  - If they tell you to help move things around or clean-up, you must comply.
- Even if you plan to mentor in an overflow room (such as for Physics), you must still check in with a head mentor at the beginning of the Walk-in.
  
## Too many students!

- Never feel obligated to stay later than 9pm.
  - Let the student know they can book an appointment
- Notify the QCL Directors if you feel unsafe.