# Forms and Surveys

## Check-in Form

- Personal QR code
  - Located on the back of your badge
- Do it for any session, such as Walk-in or One-on-one
- SUPER IMPORTANT

## Exit Survey

- Redirects after Check-in form is submitted
- Remind the student to do it after the session is done
  - Some students think they need to do it before the session; tell them to wait.


## Mini Teaching Schedule

- All mentors to are welcome to volunteer their name to do a mini teaching.

## Self-Evaluation Form

- Done by each Mentor at the end of the semester.
  - Required for all mentors, whether you plan to return or not.
- This data is VERY important to us and helps us fund the QCL.

## Student Body Evaluation

- Done by Mentors near the end of the semester.
- Gives us your perspective on how students are doing with their academics and their work/life balance.

## End of Semester Survey

- Mentors are not too involved in this, but are free to fill them out.
- We get low responses, so feel free to market the survey for us.