# Returning and Graduating Mentors

## Returning Veteran Mentors

- Fill out the Rehire Form sent to you by the QCL Directors
- You should be in the Payroll system fairly quickly
  - If you are a non-CMC student, it might take a little longer, but likely not too long. 
- You should have card access to the QCL fairly quickly
  - If you are a non-CMC student, you will have to go to Story House to get that setup. The QCL Admin. Assistant will give you instructions.
- Check if you still have access to the Discord Server and turn on push notifications on your phone.
  - If you lost access, contact the Asst. Director to regain access.
- Fill out the Availability Worksheet, which is linked in the #resources channel in Discord

## Taking a Semester Off

- Sometimes you need to go abroad or semester just get tough, so if you don't think you have enough bandwidth to be an effective QCL Mentor, feel free to take a semester off.
  - Note that if you make this decision in the middle of the semester, that semester will not count as a "full semester" worked as a Mentor.
- Just discuss it with the QCL Directors.
- You will lose the "Mentor role" in the QCL Discord Server and no longer have access to the Mentor channels, but you will still have the "Student role."
  - Your private chat will remain.
  - We strongly recommend you do not leave the server, in case you return.
- Your picture and profile may remain on the QCL Mentors webpage till after you graduate.

## Graduating

- If you are eligible for a QCL Stole, come by and pick one up (and wear it over all the other ones!)
- The QCL Directors will likely "connect" to you on LinkedIn
- You will lose the "Mentor" and "Student" roles in the QCL Discord, but will have the "Alumni" role, which gives you a very limited access to channels.
  - Your private chat will remain.
  - If you really would rather leave the server at this time, please say a good by message in the private chat. We'll miss you...
